
	script.Parent.RanBattery.Disabled = false
	wait(5)
	script.Parent.UseLight.BrickColor = BrickColor.new("Lime green")
	wait(0.05)
	script.Parent.UseLight.BrickColor = BrickColor.new("Really black")
	wait(0.2)
	script.Parent.UseLight.BrickColor = BrickColor.new("Lime green")
	wait(0.05)
	script.Parent.UseLight.BrickColor = BrickColor.new("Really black")
	wait(0.2)
	script.Parent.UseLight.BrickColor = BrickColor.new("Lime green")
	wait(0.05)
	script.Parent.UseLight.BrickColor = BrickColor.new("Really black")
	wait(0.2)
	script.Parent.UseLight.BrickColor = BrickColor.new("Lime green")
	wait(0.05)
	script.Parent.UseLight.BrickColor = BrickColor.new("Really black")
	wait(0.2)
	script.Parent.UseLight.BrickColor = BrickColor.new("Lime green")
	wait(0.05)
	script.Parent.UseLight.BrickColor = BrickColor.new("Really black")
	wait(0.2)
	script.Parent.UseLight.BrickColor = BrickColor.new("Lime green")
	wait(0.05)
	script.Parent.UseLight.BrickColor = BrickColor.new("Really black")
	wait(0.2)
